### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by adarsh-site** [Sakshamjain98/Doc_Man#11]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started

hey @Sakshamjain98 , please assign this issue to me.

**Comment by krishnas005** [comment]
Documentation is not clear in this project. @Sakshamjain98 assign this to me under GSSOC'24

**Comment by adarsh-site** [comment]
@krishnas005 bro please stop commenting on issue opened by someone else. Specially if he/she is asking the admin to assign it.

**Comment by krishnas005** [comment]
@jinx-vi-0 There are no guidelines regarding this. Anyone can request to get assigned it up to PA whom they assign

**Comment by adarsh-site** [comment]
@krishnas005 It will be assigned to the person raising the issue or the first one asking for it. I know there are no such guidelines. Its just a piece of advice from my side. If you like it take it or just ignore. Anyway good luck!

**Comment by krishnas005** [comment]
@jinx-vi-0  Fine!! Actually I am new to open-source so looking for first assignation of issues.
