### ISSUE TITLE
Add README.md File

### ISSUE THREAD

**Issue by shailifadadu** [Sakshamjain98/Doc_Man#4]
Readme is needed so that contributors can know what your project is about..

**Comment by ira-mane** [comment]
@shailifadadu  The project already has a readme file .  doc-man/README.md

**Comment by shailifadadu** [comment]
Okay.. But @ira-mane  I would suggest to add Code Of Conduct file as well

**Comment by shailifadadu** [comment]
I can add that file. If u can assign me this issue

**Comment by shailifadadu** [comment]
And Also @ira-mane readme file should be there outside that folder... I would also like to work upon this issue. Can u assign me this issue as well!!

**Comment by ira-mane** [comment]
@shailifadadu , I am no way associated to the project ,So how would I assign you the issue 😅 You should check who is the project admin for the project. and tag them.  I was just telling you that the readme file is already there in the project incase you haven't already checked that. ✌🏽

**Comment by shailifadadu** [comment]
> @shailifadadu , I am no way associated to the project ,So how would I assign you the issue 😅 You should check who is the project admin for the project. and tag them. I was just telling you that the readme file is already there in the project incase you haven't already checked that. ✌🏽

Okay okay... @ira-mane I haven't seen it and tagged u 😅

**Comment by shailifadadu** [comment]
@Sakshamjain98 can u assign me this issue..!!
